version: "3.9"

services:
  site:
    container_name: "dqAnalyzer"
    build: .
    image: egon.io
    ports:
      - "9080:80"
    environment:
    # Provide the Url of the dqanaylzer backend here
      - VITE_BACKEND_URL=
    # Prove the Url of the Grafana Dashboard here
    - GRAFANA_RESULT_DASHBOARD=  
