version: "3.9"

services:
  site:
    container_name: "dqAnalyzer"
    build: .
    image: egon.io
    ports:
      - "9080:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8888/

  # rabbit:
  #   container_name: "api-rabbit"
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672:15672"
  #     - "5672:5672"
  #   healthcheck:
  #     test: rabbitmq-diagnostics check_port_connectivity
  #     interval: 2s
  #     timeout: 5s
  #     retries: 20
  #     start_period: 5s
